Add Artea, Fix RE:SS3D
spacestation13/SS13-Codebases pull request #29
Opened 2024-01-10 17:13 UTC by RimiNosha

RE:SS3D is a spiritual successor, and has no code commonality between the original and itself.
Source: https://ss3d.space/about/

And Artea Station is my own codebase (insert self shill here), which I've been running for almost a year now. Thought I'd get it listed here, seeing as it made the unofficial list made a while back.

2024-01-10 18:53 UTC, ZeWaka requested changes
Can you fix desert rose to be less cramped

2024-01-10 18:53 UTC, ZeWaka commented
> RE:SS3D is a spiritual successor, and has no code commonality

It has asset commonality though, which is why I made it a black arrow.

2024-01-13 23:31 UTC, RimiNosha commented
Ah, then I'll return the arrow if you'd prefer it that way, and I'll see what I can do about that cramped-ness.

2025-06-11 07:10 UTC, ZeWaka commented
Stale

2025-06-11 07:10 UTC, closed without merging